config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'

  resources :tasks do
    patch :check_user_answer, on: :member
  end

  resources :users

  get 'sign_up' => 'registration#new', as: 'sign_up'
  post 'sign_up' => 'registration#create'
  get 'sign_in' => 'sessions#new', as: 'sign_in'
  post 'sign_in' => 'sessions#create', as: 'log_in'
  delete 'logout' => 'sessions#destroy', as: 'logout'
  get 'password' => 'passwords#edit', as: 'edit_password'
  patch 'password' => 'passwords#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  
  attribute :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :creator, class_name: "User"
  attr_accessor :user_answer
  validates :title, presence: true, length: { minimum: 5 }
  validates :answer, presence: true, length: { minimum: 1 }
end

app/models/user.rb
class User < ApplicationRecord
    # adds virtual attributes for authentication
    has_secure_password
    has_many :tasks, foreign_key: 'creator_id'
    # validates email
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :set_current_user
    
    def set_current_user
        Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
    end
    
    def require_user_logged_in!
        redirect_to sign_in_path, alert: 'You must be signed in' if Current.user.nil?
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

    before_action :require_user_logged_in!

    def edit; end
    
    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: 'Password Updated'
        else
            render :edit
        end
    end

    private def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: 'Successfully created account'
        else
            render :new
        end
    end

    private def user_params
      # strong parameters
      params.require(:user).permit(:email, :password, :password_confirmation, :nickname)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new; end

    def create
        user = User.find_by(email: params[:email])

        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: 'Logged in successfully'
        else
            flash.now[:alert] = 'Invalid email or password'
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: 'Logged Out'
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = Task.all
    end

    def new
        require_user_logged_in!
        @task = Task.new
        @user_answer = ""
    end

    def show
        @task = Task.find(params[:id])
    end

    def check_user_answer
        require_user_logged_in!
        @task = Task.find(params[:id])
        @user_answer = params[:task][:user_answer]
        @result = ""
        if @task.answer == @user_answer
            task_ids = Current.user.completed_task_ids.split(",")
            already_answered = task_ids.include? @task.id.to_s
            if (!already_answered)
                task_ids << @task.id.to_s
                Current.user.update_attribute(:completed_task_ids, task_ids.join(","))
            end
            @result = "Right answer!"
        else
            @result = "Wrong answer" + @user_answer + "|"
        end
        redirect_to @task, notice: @result
    end

    def edit
        require_user_logged_in!
        @task = Task.find(params[:id])
        access_check
    end

    def update
        require_user_logged_in!
        @task = Task.find(params[:id])
        access_check

        if @task.update(task_params)
            redirect_to @task
        else
            render :edit
        end
    end
    
    def destroy
        require_user_logged_in!
        @task = Task.find(params[:id])
        access_check

        @task.destroy
        redirect_to tasks_path
    end

    def create
        require_user_logged_in!
        @task = Task.new(task_params)
        @task.creator = Current.user
        Current.user.tasks << @task
        @user_answer = ""

        if @task.save
            redirect_to @task
        else
            render :new
        end
    end

    private def task_params
        require_user_logged_in!
        params.require(:task).permit(:title, :body, :answer)
    end

    private def access_check
        redirect_to @task, alert: "You don't have access to this task" if @task.creator != Current.user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/solved_tasks_helper.rb
module SolvedTasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'headers', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="p-3 mb-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <span href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
          <%= link_to image_tag("logo.png", style: 'height:auto;width:60%;', :class => "bi me-2"), root_path %>
        </span>

        <% if Current.user.nil? %>
          <ul class="nav col-12 col-lg-auto me-lg-auto mt-2 justify-content-center mb-md-0">
            <li><span class="nav-link px-2 link-dark"><%= button_to "Sign Up", sign_up_path, :class => "btn btn-light" %></span></li>
            <li><span class="nav-link px-2 link-dark"><%= button_to "Sign In", sign_in_path, :class => "btn btn-light" %></span></li>
          </ul>
        <% else %>
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><span class="nav-link px-2 link-dark"><%= button_to "New task", new_task_path, method: :get, :class => "btn btn-light" %></span></li>
            <li><span class="nav-link px-2 link-dark"><%= button_to "Log out", logout_path, method: :delete, :class => "btn btn-light" %></span></li>
          </ul>
        <% end %>
      </div>
    </div>
    </header>

    <div>
      <div class="container">
        <% if notice != nil %>
          <p class="alert alert-primary"><%= notice %></p>
        <% end %>
        <% if alert != nil %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2>Edit task</h2>
<%= form_for :task, url: task_path(@task), method: :patch do |f| %>
    <% if @task.errors.any? %>
        <% @task.errors.full_messages.each do |msg| %>
            <div><%= msg %></div>
        <% end %>
    <% end %>

    <p>
        Title<br>
        <%= f.text_field :title, { :class => "form-control"} %>
    </p>
    <p>
        The task<br>
        <%= f.text_area :body, { :class => "form-control"} %>
    </p>
    <p>
        Answer to the task<br>
        <%= f.text_field :answer, { :class => "form-control"} %>
    </p>

    <p>
        <%= f.submit "Submit", { :class => "btn btn-success"} %>
    </p>
<% end -%>

app/views/tasks/index.html.erb
<h1>All tasks</h1>
<% @tasks.each do |task| %>
    <p>
        <h3>
            <%= link_to task.title, task_path(task), style: "text-decoration:none; color:black;" %>
        </h3>
    </p>
<% end %>

app/views/tasks/new.html.erb
<h2>Add new task</h2>
<%= form_for :task, url: tasks_path do |f| %>
    <% if @task.errors.any? %>
        <% @task.errors.full_messages.each do |msg| %>
            <div><%= msg %></div>
        <% end %>
    <% end %>

    <p>
        Title<br>
        <%= f.text_field :title, { :class => "form-control"} %>
    </p>
    <p>
        The task<br>
        <%= f.text_area :body, { :class => "form-control"} %>
    </p>
    <p>
        Answer to the task<br>
        <%= f.text_field :answer, { :class => "form-control"} %>
    </p>

    <p>
        <%= f.submit "Submit", { :class => "btn btn-success"} %>
    </p>
<% end -%>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= markdown(@task.body) %></p>

<hr>

<p>
    posted by <%= link_to @task.creator.nickname, user_path(@task.creator) %>
</p>

<p>
    <% if @task.creator == Current.user %>
        <%= link_to "Edit", edit_task_path(@task) %>
        <%= link_to "Delete", task_path(@task), method: :delete, data: { confirm: "Are you sure you want to delete the task?" } %>
    <% end %>
</p>

<hr>

<% if !Current.user.nil? %>
    <% if Current.user.completed_task_ids.split(",").include? @task.id.to_s %>
        You have already done this task<br>
    <% else %>
        <%= form_for @task, :url => { :action => "check_user_answer" } do |f| %>
        <p>
            Your answer:<br>
            <%= f.text_field :user_answer, { :class => "form-control"} %>
        </p>

        <p>
            <%= f.submit "Check", { :class => "btn btn-success"} %>
        </p>
        <% end %>
    <% end %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.nickname %></h1>
<p><%= @user.discription %></p>
<p>
    Created tasks:
    <% @user.tasks.each do |t| %>
        <div>
            <p>
                <%= link_to t.title, task_path(t) %>
            </p>
        </div>
    <% end %>
</p>
<p>
    Completed tasks:
    <% @user.completed_task_ids.split(',').each do |t| %>
        <div>
            <p>
                <%= link_to Task.find(t.to_i).title, task_path(Task.find(t.to_i)) %>
            </p>
        </div>
    <% end %>
</p>